apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: agshin13/api-gateway:s3
        imagePullPolicy: IfNotPresent
        name: api-gateway-container
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://service-discovery:8761/eureka/"
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"
        readinessProbe:
          httpGet:
            port: 8088
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8088
            path: /actuator/health/liveness
      restartPolicy: Always
             

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: api-gateway
  sessionAffinity: None
  type: LoadBalancer

  
  
  