apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: agshin13/email-service:s2
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: APP_MAIL_USERNAME
              value: "katrina.smitham52@ethereal.email"
            - name : APP_MAIL_PASSWORD
              value: "af2pdgKxf7ewg9k1wW"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
