apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: service-discovery
  name: service-discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - image: agshin13/service-discovery:s2
        imagePullPolicy: IfNotPresent
        name: service-discovery-container
        resources:
         limits:
           memory: "1Gi"
         requests:
           memory: "512Mi"
        env:
          - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
            value: "false" 
          - name: EUREKA_CLIENT_FETCH_REGISTRY
            value: "false"
        readinessProbe:
          httpGet:
            port: 8761
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8761
            path: /actuator/health/liveness
      restartPolicy: Always
             

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
    - port: 8761
      targetPort: 8761


  
  
  