apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: agshin13/user-service:s2
        imagePullPolicy: IfNotPresent
        name: user-service-container
        resources:
         limits:
           memory: "1Gi"
         requests:
           memory: "512Mi"
        env:
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "12345"
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://service-discovery:8761/eureka/"
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql:3306/user"

        startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 40
          periodSeconds: 10
      restartPolicy: Always
             

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

  
  
  